// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciYonetimi.Data.EntityFramework;

namespace OgrenciYonetimi.Data.Migrations
{
    [DbContext(typeof(OgrenciYonetimDbContext))]
    [Migration("20190405182004_CreateDersTable")]
    partial class CreateDersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OgrenciYonetimi.Data.DataModels.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DersAdi");

                    b.Property<int>("SinifId");

                    b.HasKey("DersId");

                    b.HasIndex("SinifId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("OgrenciYonetimi.Data.DataModels.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi");

                    b.Property<string>("Cinsiyet");

                    b.Property<int>("No");

                    b.Property<int>("SinifId");

                    b.Property<string>("Soyadi");

                    b.HasKey("OgrenciId");

                    b.HasIndex("SinifId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciYonetimi.Data.DataModels.Sinif", b =>
                {
                    b.Property<int>("SinifId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi");

                    b.HasKey("SinifId");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("OgrenciYonetimi.Data.DataModels.Ders", b =>
                {
                    b.HasOne("OgrenciYonetimi.Data.DataModels.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OgrenciYonetimi.Data.DataModels.Ogrenci", b =>
                {
                    b.HasOne("OgrenciYonetimi.Data.DataModels.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
